### PR TITLE
Add ability to use dynamic spaces

### PR DESCRIPTION
**Pull request by mwz**
FYI @dlaird-ovo I've opened a PR with your changes against a dev branch, where we can keep our custom changes and sync with main from the upstream repo.

The plan is to tag from this branch and reference those in our backstage deps.

This might not run the tests yet as I still need to sort out the workflows, but I'll still open the PR for now.

@dlaird-ovo are those changes up-to-date or have you actually made any other changes since then?

### CODE REVIEW

**Comment by dlaird-ovo** [comment]
Will try and take a look today / tomorrow as I am clearing my backlog of tasks that suddenly built up.

**Comment by dlaird-ovo** [comment]
Finally reviewed the changes - with those in repo and locally.  All looks good to me.

**Comment by dlaird-ovo** [comment]
I had thought about that before - but then completely forgot about it!

**Comment by mwz** [comment]
Hi @dlaird-ovo, would you be able to review and merge the following PR to progress this?
https://github.com/dlaird-ovo/backstage-plugin-confluence/pull/1?

**Comment by dlaird-ovo** [comment]
Done - Merged :-)

**Comment by mwz** [comment]
Perfect, thank you Dan.

**Pull request merged**
